version: '3.8'

services:
  mongo_db:
    image: mongo:latest
    container_name: mongo_service
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
    volumes:
      - ./mongo_db:/docker-entrypoint-initdb.d
      - mongo-data:/data/db
  rust_query:
    container_name: rust_query_server
    build:
      context: ./rust_query_api
      dockerfile: Dockerfile
    environment:
      MONGODB_URI: mongodb://${MONGO_INITDB_ROOT_USERNAME}:${MONGO_INITDB_ROOT_PASSWORD}@mongo_db:${MONGO_HOST_PORT}/${MONGO_INITDB_DATABASE}?authSource=admin 
      DATABASE_NAME: ${MONGO_INITDB_DATABASE}
      RUST_LOG: info 
    depends_on:
      - mongo_db 
    restart: unless-stopped
  web-app:
    build:
      context: ./web_app 
      dockerfile: Dockerfile
    container_name: web-app-container 
    ports:
      - "9999:9999" 
    environment:
      - INFERENCE_API_URL=http://host.docker.internal:9990/predict #python_inference_api host and port
      - QUERY_API_URL=http://rust_query:8080/query #rust_query server API host and port
    depends_on:
      - rust_query
    restart: unless-stopped

volumes:
  mongo-data:
    driver: local
