version: '3.8'

services:
  mongo_db:
    image: mongo:latest
    container_name: mongo_service
    restart: always
    ports:
      - "${MONGO_HOST_PORT:-27017}:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
    volumes:
      - ./mongo_db:/docker-entrypoint-initdb.d
      - mongo-data:/data/db

volumes:
  mongo-data:
    driver: local
