version: '3.8'

services:
  mongo_db:
    image: mongo:latest
    container_name: mongo_service
    restart: always
    ports:
      - "${MONGO_HOST_PORT:-27017}:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
    volumes:
      - ./mongo_db:/docker-entrypoint-initdb.d
      - mongo-data:/data/db
  web-app:
    build:
      context: ./web_app 
      dockerfile: Dockerfile
    container_name: web-app-container 
    ports:
      - "9999:9999" 
    environment:
      - INFERENCE_API_URL=http://localhost:9990/predict #python_inference_api host and port
    depends_on:
      - mongo_db
    restart: unless-stopped

volumes:
  mongo-data:
    driver: local
