import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "NL2MQ",
  description: "Generated by paulc-1212",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <div className="flex flex-col h-screen bg-gray-950 text-gray-100 font-sans">
          <header className="p-3 border-b border-cyan-500/20 flex justify-start items-center bg-gray-900 shadow-md">
            <div className="flex items-center text-lg font-medium text-gray-100">
              〄 NL2MQ
            </div>
          </header>
          <main className="flex-grow flex flex-col items-center p-4 overflow-y-auto">
            {children}
          </main>
          <footer className="text-center text-xs text-gray-600 mt-3 pb-1">Natural Language to MongoDB Query Interface by @paulc-1212</footer>
        </div>
      </body>
    </html>
  );
}
